pipeline:
  name: Build Sample-ReactJS
  identifier: Build_Sample_ReactJS_1689131660247
  projectIdentifier: Test
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm install
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1689131639217
        repoName: https://github.com/LetsDevops9/Sample-ReactJS.git
        build: <+input>
