pipeline:
  identifier: Build_Sample_ReactJS_1689133594737
  name: Build Sample-ReactJS
  orgIdentifier: default
  projectIdentifier: New
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1688873541346
        repoName: LetsDevops9/Sample-ReactJS
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Completed"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
